version: '3.3'

services:

  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root


  adminer:
    image: adminer
    ports:
      - 8082:8080