-- MySQL Script generated by MySQL Workbench
-- Fri Jul 10 15:59:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `online_shop` ;

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_shop` DEFAULT CHARACTER SET utf8 ;
USE `online_shop` ;

-- -----------------------------------------------------
-- Table `online_shop`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_shop`.`users` ;

CREATE TABLE IF NOT EXISTS `online_shop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `photo` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_shop`.`orders` ;

CREATE TABLE IF NOT EXISTS `online_shop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'NEW',
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `online_shop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_shop`.`item` ;

CREATE TABLE IF NOT EXISTS `online_shop`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `total_amount` INT NOT NULL,
  `sold_amount` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_shop`.`roles` ;

CREATE TABLE IF NOT EXISTS `online_shop`.`roles` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`users_has_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_shop`.`users_has_roles` ;

CREATE TABLE IF NOT EXISTS `online_shop`.`users_has_roles` (
  `users_id` INT NOT NULL,
  `roles_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_id`, `roles_name`),
  INDEX `fk_users_has_roles_roles1_idx` (`roles_name` ASC) VISIBLE,
  INDEX `fk_users_has_roles_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `online_shop`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`roles_name`)
    REFERENCES `online_shop`.`roles` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`orders_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_shop`.`orders_has_item` ;

CREATE TABLE IF NOT EXISTS `online_shop`.`orders_has_item` (
  `orders_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `amount` INT NOT NULL,
  INDEX `fk_orders_has_item_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_orders_has_item_orders1_idx` (`orders_id` ASC) VISIBLE,
  PRIMARY KEY (`orders_id`, `item_id`),
  CONSTRAINT `fk_orders_has_item_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `online_shop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `online_shop`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
